### ISSUE TITLE
Blocker (Plakton) richtig einstellen

### ISSUE THREAD

**Issue by MarekW98** [JohannesLks/AwesomeGame#52]
Als Möglichkeit könnte man den Blocker verreinfachen. Aktuell kommt dieser sehr häufig vor. 

Mein Vorschlag wäre, dass man diesen auf die Anzahl der Schüsse die man ausgibt macht. Als Beispiel alle 10 Schüsse wird ein Blocker an der Stelle erscheinen wo man schießt. Nur in der horizontalen fix. Der Blocker kann ja weiterhin in der vertikalen weiterhin irgendwo erscheinen sei es weiter oben oder unten.

So hat man als Tryharder die möglichkeit spielerein für sich auszunutzen und die schüsse für sich abzuzählen um den 10ten blocker dann günstig zu setzen

**Comment by Jonasph7** [comment]
Gute Idee. Da musste auf jeden Fall was geändert werden. Ich habe die Spawn Rate angepasst, sodass die Blocker nicht ganz so häufig spawnen. Außerdem können jetzt nur noch max. 8 Planktons spawnen. Die behindern genug. Noch mehr und das Game tendiert dazu unspielbar zu werden...
