### ISSUE TITLE
Verschiedene Gegner

### ISSUE THREAD

**Issue by JohannesLks** [JohannesLks/AwesomeGame#6]
Es soll nicht nur eine Art von Gegner geben sondern mehrere. Diese unterscheiden sich in Größe, Geschwindigkeit und Anzahl der Leben. Sie müssen auch unterschiedlich aussehen.

**Comment by Jonasph7** [comment]
also die verschiedenen gegner typen, die du hier reingepostet hast, habe ich integriert

**Comment by Jonasph7** [comment]
@JohannesLks @MarekW98 @Er1kJungjo wie besprochen. alles rund um gegner/blocker wird verfeinert. z.b. speed, größe, health (tank braucht 5 hits, zieht nur 10 hp ab ...)

da würde ich mich drum kümmern, da ich mich halbwegs bzgl. der gegner/blocker auskenne
