### ISSUE TITLE
Fische sollten sich nicht in gerader Linie bewegen

### ISSUE THREAD

**Issue by JohannesLks** [JohannesLks/AwesomeGame#82]
Man könnte die Fische sich in einer Sinuskurve bewegen lassen

**Comment by JohannesLks** [comment]
Leider Spawnen die Gegner nicht mehr im Spielfeld, sondern zu niedrig auf Höhe von Mr. Krabs

**Comment by Jonasph7** [comment]
@JohannesLks ich weiß genau, was du meinst. Die Sinuswelle sieht relativ gut aus, aber sie spawnen plötzlich ganz unten auf Höhe von Mr. Krabs. alle y-Spawn-Beschränkungen scheinen ihnen egal zu sein. Wtf. Bist du schon weiter oder ist das auch noch dein letzter Stand?

**Comment by JohannesLks** [comment]
@Jonasph7 habe echt viel rumprobiert und nichts hatte funktioniert. Irgendwie ignoriert er die Y Grenze und ich verstehe auch noch nicht warum.

**Comment by Jonasph7** [comment]
@JohannesLks Alles klar, dann sind wir hier ca. auf dem gleichen Stand. Das kriegen wir schon noch hin! :)
